version: '3'
services:
  bme280:
    build: ./bme280/
    environment:
      - INFLUXDB_SEVER=thp-influxdb
    devices:
      - "/dev/i2c-1"
    depends_on:
      - influxdb
    restart: always
  co2:
    build: ./co2/
    environment:
      - INFLUXDB_SEVER=thp-influxdb
    devices:
      - "/dev/ttyS0"
    depends_on:
      - influxdb
    restart: always
  influxdb:
    image: hypriot/rpi-influxdb
    container_name: "thp-influxdb"
    ports:
      - 8086:8086
    environment:
      - PRE_CREATE_DB=thp
    volumes:
      - ./influxdb:/data
    restart: always
  grafana:
    image: grafana/grafana:7.1.1
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards/json:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    restart: always
