name: Raspberrypi-github-actions

on:
 push:
  branches: [ "main" ]

jobs:
  raspberrypi-test:
    runs-on: [self-hosted, linux, arm]
    steps:
      - name: deploy 
        run: |
          echo "Deploy Start"
          pwd
          whoami 
          echo "Deploy Start"
